In [7]:
import numpy as np
import pandas as pd

In [8]:
df_train = pd.read_csv('train.csv')
df_test = pd.read_csv('test.csv')
df_sub = pd.read_csv('sample_submission.csv')

In [9]:
df_train.head()

,model,year,motor_type,running,wheel,color,type,status,motor_volume,price
0,toyota,2022,petrol,3000 km,left,skyblue,sedan,excellent,2.0,24500
1,mercedes-benz,2014,petrol,132000 km,left,black,sedan,excellent,2.0,25500
2,kia,2018,petrol,95000 miles,left,other,sedan,excellent,2.0,11700
3,mercedes-benz,2002,petrol,137000 miles,left,golden,sedan,excellent,3.2,12000
4,mercedes-benz,2017,petrol,130000 km,left,black,sedan,good,2.0,26000

In [10]:
df_test.head()

,Id,model,year,motor_type,running,wheel,color,type,status,motor_volume
0,0,kia,2020,petrol,24000 km,left,black,sedan,excellent,2.0
1,1,nissan,2017,petrol,85000 miles,left,white,suv,excellent,2.0
2,2,hyundai,2021,petrol,30000 miles,left,white,sedan,excellent,2.0
3,3,kia,2018,petrol,53000 miles,left,silver,sedan,excellent,2.0
4,4,mercedes-benz,2003,petrol,230000 km,left,black,Universal,normal,1.8

In [11]:
df_sub

      Id  price
0      0     38
1      1  20549
2      2   3927
3      3   5572
4      4  28598
..   ...    ...
406  406   2514
407  407  20307
408  408  27274
409  409  14422
410  410   9376

[411 rows x 2 columns]

In [12]:
df_train.info()

<class 'pandas.DataFrame'>
RangeIndex: 1642 entries, 0 to 1641
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   model         1642 non-null   str
 1   year          1642 non-null   int64
 2   motor_type    1642 non-null   str
 3   running       1642 non-null   str
 4   wheel         1642 non-null   str
 5   color         1642 non-null   str
 6   type          1642 non-null   str
 7   status        1642 non-null   str
 8   motor_volume  1642 non-null   float64
 9   price         1642 non-null   int64
dtypes: float64(1), int64(2), str(7)
memory usage: 128.4 KB

In [13]:
df_test.info()

<class 'pandas.DataFrame'>
RangeIndex: 411 entries, 0 to 410
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Id            411 non-null    int64
 1   model         411 non-null    str
 2   year          411 non-null    int64
 3   motor_type    411 non-null    str
 4   running       411 non-null    str
 5   wheel         411 non-null    str
 6   color         411 non-null    str
 7   type          411 non-null    str
 8   status        411 non-null    str
 9   motor_volume  411 non-null    float64
dtypes: float64(1), int64(2), str(7)
memory usage: 32.2 KB

In [14]:
df_test = df_test.drop('Id', axis=1)

In [15]:
set(df_test['model']).difference(set(df_train['model']))

set()

In [16]:
from sklearn.preprocessing import LabelEncoder

In [17]:
label = LabelEncoder()

In [18]:
df_train['model'] = label.fit_transform(df_train['model'])

In [19]:
df_test['model'] = label.transform(df_test['model'])

In [20]:
label.classes_

array(['hyundai', 'kia', 'mercedes-benz', 'nissan', 'toyota'],
      dtype=object)

In [21]:
set(df_test['motor_type']).difference(set(df_train['motor_type']))

set()

In [22]:
df_train['motor_type'] = label.fit_transform(df_train['motor_type'])
df_test['motor_type'] = label.transform(df_test['motor_type'])

In [23]:
df_train['running'] = df_train['running'].apply(lambda x: int(x.split()[0]) if x.split()[-1] == 'km' else int(x.split()[0]) * 1.6)

In [24]:
df_test['running'] = df_test['running'].apply(lambda x: int(x.split()[0]) if x.split()[-1] == 'km' else int(x.split()[0]) * 1.6)

In [25]:
set(df_test['wheel']).difference(set(df_train['wheel']))

{'right'}

In [26]:
df_test['wheel'].value_counts()

wheel
left     409
right      2
Name: count, dtype: int64

In [27]:
df_train['wheel'].value_counts()

wheel
left    1642
Name: count, dtype: int64

In [28]:
df_train = df_train.drop('wheel', axis=1)
df_test = df_test.drop('wheel', axis=1)

In [29]:
df_train['color']

0       skyblue
1         black
2         other
3        golden
4         black
         ...
1637      white
1638      black
1639       blue
1640      black
1641      white
Name: color, Length: 1642, dtype: str

In [30]:
set(df_test['color']).difference(set(df_train['color']))

set()

In [31]:
df_train['color'] = label.fit_transform(df_train['color'])
df_test['color'] = label.transform(df_test['color'])

In [32]:
df_train['type'] = label.fit_transform(df_train['type'])
df_test['type'] = label.transform(df_test['type'])

In [33]:
set(df_test['status']).difference(set(df_train['status']))

set()

In [34]:
df_train['status'] = label.fit_transform(df_train['status'])
df_test['status'] = label.transform(df_test['status'])

In [35]:
X_train = df_train.drop('price', axis=1)
y_train = df_train['price']
X_test = df_test.copy()

In [36]:
from sklearn.model_selection import train_test_split

In [37]:
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.33, random_state=42)

In [38]:
from sklearn.linear_model import LinearRegression

In [39]:
model = LinearRegression()

In [40]:
X_train

      model  year  motor_type   running  color  type  status  motor_volume
308       1  2019           3   48800.0      2     5       1           2.0
430       1  2019           3   44000.0      4     5       1           1.6
370       0  2018           3   92800.0      7     5       1           1.6
678       4  2018           3      52.0     14     5       1           1.8
181       0  2017           3  110400.0      1     5       1           2.0
...     ...   ...         ...       ...    ...   ...     ...           ...
1130      3  2017           3  107200.0      2     6       1           2.5
1294      0  2014           3  138000.0      1     5       4           2.0
860       2  2005           1  247000.0     14     5       1           2.6
1459      3  2018           3   91000.0     16     2       1           2.0
1126      2  1998           3  179000.0      1     5       1           2.0

[1100 rows x 8 columns]

In [67]:
model.fit(X_train, y_train)

LinearRegression()

In [68]:
y_pred = model.predict(X_val)

In [69]:
from sklearn.metrics import mean_squared_error, mean_absolute_error

In [70]:
mean_absolute_error(y_pred, y_val)

3331.9129813096692

In [72]:
y_train.mean()

np.float64(16005.084545454545)

In [73]:
y_pred = model.predict(X_test)

In [74]:
df_sub['price' ] = y_pred

In [75]:
df_sub.to_csv('sub.csv', index=False, index_label=False)